// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc7Z0wpaK5mPRUJZGksCrbEkcURSK7rpg',
    appId: '1:816570173156:android:2e6d3acd3e8efe4732cef1',
    messagingSenderId: '816570173156',
    projectId: 'blinders-hunter',
    databaseURL: 'https://blinders-hunter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'blinders-hunter.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-SsrIY3XYrzttoNBO3s54rrI0xSnypBk',
    appId: '1:816570173156:web:98de66af4cfc9dd632cef1',
    messagingSenderId: '816570173156',
    projectId: 'blinders-hunter',
    authDomain: 'blinders-hunter.firebaseapp.com',
    databaseURL: 'https://blinders-hunter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'blinders-hunter.firebasestorage.app',
    measurementId: 'G-XNLJQ48C9W',
  );
}
